Updates code formatting

diff --git a/.github/workflows/code-style.yml b/.github/workflows/code-style.yml
--- a/.github/workflows/code-style.yml
+++ b/.github/workflows/code-style.yml
@@ -55,11 +55,11 @@ jobs:
         echo "::set-output name=package::"${response_package}""
         echo "::set-output name=tests::"${response_tests}""
     - name: Check if site is down
-        # Fail the job and exit if code style still needs formatting
-        if: steps.black.outputs.packages != 0 || steps.black.outputs.tests != 0
-        run: |
-          echo "Code fails style format tests"
-          exit 1
+      # Fail the job and exit if code style still needs formatting
+      if: steps.black.outputs.packages != 0 || steps.black.outputs.tests != 0
+      run: |
+        echo "Code fails style format tests"
+        exit 1
     - name: Format event type name
       id: event
       run: |
