Updates doc build code and actions code comments

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -1,9 +1,16 @@
+# ####################################################################
+# GitHub workflow action file
+# Build the Sphinx documentation on the GitHub workflow runner
+# Pushes the docs to the gh-pages branch, enabling the website
+# ####################################################################
+
 # Content inspired from these sources
 # https://github.com/ammaraskar/sphinx-action-test/blob/master/.github/workflows/default.yml
 # https://www.innoq.com/en/blog/github-actions-automation/
 # https://github.com/marketplace/actions/publish-to-git
 # https://github.com/seanmiddleditch/gha-publish-to-git/blob/master/entrypoint.sh
 # https://github.com/JacksonMaxfield/github-pages-deploy-action-python/blob/master/entrypoint.sh
+# https://stackoverflow.com/questions/58257140/unable-to-commit-and-push-back-changes-made-by-github-action-invalid-user?rq=1
 
 # This workflow action builds and pushes any recent changes to the sphinx documentation to the gh-pages branch
 
@@ -16,7 +23,7 @@ on:
     branches:
       - master
 
-# Set environment variables so this workflow action is easy tore-use in other repos
+# Set environment variables so this workflow action is easy to re-use in other repos
 env:
   DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
   REPO_NAME: cmatools
@@ -30,8 +37,6 @@ jobs:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0 # Ensure all branches are available
-        #token: $DEPLOY_TOKEN
-        #persist-credentials: false
     - name: Install dependencies
       run: |
         conda update conda
@@ -75,14 +80,13 @@ jobs:
         echo " ----------------------------------------------------------"
         echo " ----------------------------------------------------------"
 
-
         # Remove all files to ensure a new clean build of the documentation
 
         git rm -r cmatools
         git rm -r docs
         git rm -r tests
 
-        #git rm -rf .
+        git rm -rf .
 
         git clean -dfx
 
@@ -106,7 +110,8 @@ jobs:
         # Uses deploy token to allow authentication from the workflow to repo
         #git remote set-url origin "$REPO_URI"
 
-        git commit -m "Update documentation on gh-pages" -a || true
+
+        #git commit -m "Update documentation on gh-pages" -a || true
 
         echo " ----------------------------------------------------------"
         echo " ----------------------------------------------------------"
@@ -116,64 +121,65 @@ jobs:
         echo " ----------------------------------------------------------"
 
 
+        #echo "Push changes to the gh-pages branch"
+        #git push --force-with-lease origin gh-pages
+
+
+
+        # Clean up the working repo, deletes any untracked files from the current checkout out repo
+        # (force, includes directories, removes ignored files)
+        git clean -dfx
+
+        # Checkout only the directories needed to build the documentation from master
+        git checkout -f origin/master scripts/
+        git checkout -f origin/master docs/
+        git checkout -f origin/master .nojekyll
+        echo " --- Building documentation --- "
+        echo $PWD
+
+        # Build the html documentation with sphinx
+        cd scripts/docs
+        chmod +x build-sphinx-docs.sh
+        ./build-sphinx-docs.sh
+
+        echo " ---------- * ----------"
+        echo "Documentation built"
+        cd  ../..
+        echo $PWD
+        cd docs/build
+        echo $PWD
+        echo " ---------- * ----------"
+
+        # Confirm git status, for debugging
+        echo "-- git status --"
+        git status
+        echo "-- end git status --"
+        echo $PWD
+        echo " ---------- * ----------"
+
+        # Add the newly created files and directories to git
+        git add -f _static
+        git add -f _sources
+        git add -f *.html
+        git add -f *.inv
+        git add -f *.js
+        cd ../..
+        git add docs/
+
+        # Confirm git status, for debugging
+        echo "---*  git status *---"
+        git status
+        echo "-- end git status --"
+        git status
+
+        # Commit all the changes, inc message
+        # Always exit with status 0
+
+        git commit -m "Update documentation on gh-pages" -a || true
+
+        # Set the remote url for the github repo,
+        # Uses deploy token to allow authentication from the workflow to repo
+        #git remote set-url origin "$REPO_URI"
+
         echo "Push changes to the gh-pages branch"
         git push --force-with-lease origin gh-pages
-
-
-#        # Clean up the working repo, deletes any untracked files from the current checkout out repo
-#        # (force, includes directories, removes ignored files)
-#        git clean -dfx
-#
-#        # Checkout only the directories needed to build the documentation from master
-#        git checkout -f origin/master scripts/
-#        git checkout -f origin/master docs/
-#        git checkout -f origin/master .nojekyll
-#        echo " --- Building documentation --- "
-#        echo $PWD
-#
-#        # Build the html documentation with sphinx
-#        cd scripts/docs
-#        chmod +x build-sphinx-docs.sh
-#        ./build-sphinx-docs.sh
-#
-#        echo " ---------- * ----------"
-#        echo "Documentation built"
-#        cd  ../..
-#        echo $PWD
-#        cd docs/build
-#        echo $PWD
-#        echo " ---------- * ----------"
-#
-#        # Confirm git status, for debugging
-#        echo "-- git status --"
-#        git status
-#        echo "-- end git status --"
-#        echo $PWD
-#        echo " ---------- * ----------"
-#
-#        # Add the newly created files and directories to git
-#        git add -f _static
-#        git add -f _sources
-#        git add -f *.html
-#        git add -f *.inv
-#        git add -f *.js
-#        cd ../..
-#        git add docs/
-#
-#        # Confirm git status, for debugging
-#        echo "---*  git status *---"
-#        git status
-#        echo "-- end git status --"
-#        git status
-#
-#        # Commit all the changes, inc message
-#        # Always exit with status 0
-#
-#        git commit -m "Update documentation on gh-pages" -a || true
-#
-#        # Set the remote url for the github repo,
-#        # Uses deploy token to allow authentication from the workflow to repo
-#        git remote set-url origin "$REPO_URI"
-#
-#        echo "Push changes to the gh-pages branch"
-#        git push --force-with-lease origin gh-pages
