Re-order to test dev install before full install

diff --git a/.github/workflows/test-package-structure.yml b/.github/workflows/test-package-structure.yml
--- a/.github/workflows/test-package-structure.yml
+++ b/.github/workflows/test-package-structure.yml
@@ -41,6 +41,53 @@ jobs:
       run: |
         conda update conda
         conda env create -f $ENV_FILE
+
+    - name: Install the package - development install
+      run: |
+        source /usr/share/miniconda/etc/profile.d/conda.sh
+        conda activate "$CONDA_ENV"
+        pip  install -e .
+    - name: Run unit tests for version to check package test structure is working (development install)
+      id: dev
+      run: |
+        source /usr/share/miniconda/etc/profile.d/conda.sh
+        conda activate $CONDA_ENV
+        cd scripts/tests
+        chmod +x test-unit-version.sh
+        ./test-unit-version.sh
+        echo "Simple test: version has run"
+        echo "Summary of package installation (pip show)"
+        pip show $PACKAGE
+        echo " --- "
+        # Run pytest with pytest-cov to exaime the code coverage from one simple unit test (version)
+        # Capture standard error to shell script variable, discard standard out to dev null
+        error=$(pytest --cov-report= --cov=$GITHUB_WORKSPACE/cmatools $GITHUB_WORKSPACE/tests/unit/version  2>&1 > /dev/null)
+        echo " --- "
+        echo "${error}"
+        echo " --- "
+        # Capture the error to a named step output (as error)
+        echo "::set-output name=error::${error}"
+        # Set an expected, known, error message potentially generate from coverage (as message)
+        # This is a bit of a hack, it works because we know the expected error message if the dir structure does
+        # not allow the coverage test to complete
+        echo "::set-output name=message::warning: No data was collected"
+    - name: Check for error, exit if found (dev)
+      # Fail the job and exit if code style still needs formatting
+      if: contains(steps.dev.outputs.error , steps.dev.outputs.message)
+      run: |
+        echo steps.dev.outputs.error
+        echo "Package test structure causes warnings, no output for pytest coverage"
+        echo "Test fails - for a dev install"
+        exit 1
+
+    - name: Un-install the package
+      run: |
+        source /usr/share/miniconda/etc/profile.d/conda.sh
+        conda activate "$CONDA_ENV"
+        cd scripts/uninstall
+        chmod +x uninstall.sh
+        ./uninstall.sh
+
     - name: Install the package - full install
       run: |
         source /usr/share/miniconda/etc/profile.d/conda.sh
@@ -78,48 +125,4 @@ jobs:
         echo steps.full.outputs.error
         echo "Package test structure causes warnings, no output for pytest coverage"
         echo "Test fails - for a full install"
-        exit 1
-    - name: Un-install the package
-      run: |
-        source /usr/share/miniconda/etc/profile.d/conda.sh
-        conda activate "$CONDA_ENV"
-        cd scripts/uninstall
-        chmod +x uninstall.sh
-        ./uninstall.sh
-    - name: Install the package - development install
-      run: |
-        source /usr/share/miniconda/etc/profile.d/conda.sh
-        conda activate "$CONDA_ENV"
-        pip  install -e .
-    - name: Run unit tests for version to check package test structure is working (development install)
-      id: dev
-      run: |
-        source /usr/share/miniconda/etc/profile.d/conda.sh
-        conda activate $CONDA_ENV
-        cd scripts/tests
-        chmod +x test-unit-version.sh
-        ./test-unit-version.sh
-        echo "Simple test: version has run"
-        echo "Summary of package installation (pip show)"
-        pip show $PACKAGE
-        echo " --- "
-        # Run pytest with pytest-cov to exaime the code coverage from one simple unit test (version)
-        # Capture standard error to shell script variable, discard standard out to dev null
-        error=$(pytest --cov-report= --cov=$GITHUB_WORKSPACE/cmatools $GITHUB_WORKSPACE/tests/unit/version  2>&1 > /dev/null)
-        echo " --- "
-        echo "${error}"
-        echo " --- "
-        # Capture the error to a named step output (as error)
-        echo "::set-output name=error::${error}"
-        # Set an expected, known, error message potentially generate from coverage (as message)
-        # This is a bit of a hack, it works because we know the expected error message if the dir structure does
-        # not allow the coverage test to complete
-        echo "::set-output name=message::warning: No data was collected"
-    - name: Check for error, exit if found (dev)
-      # Fail the job and exit if code style still needs formatting
-      if: contains(steps.dev.outputs.error , steps.dev.outputs.message)
-      run: |
-        echo steps.dev.outputs.error
-        echo "Package test structure causes warnings, no output for pytest coverage"
-        echo "Test fails - for a dev install"
         exit 1
